### ISSUE TITLE
Create README.md and other documentations in Persian

### ISSUE THREAD

**Issue by mhzendehpey** [hezarai/hezar#103]
As a Persian library for the Persian-speaking community, I think providing documentation in Persian is essential.

**Comment by pooya-mohammadi** [comment]
@arxyzan we can get help from the community for completing this task.
I also think this is an essential feature we should add

**Comment by arxyzan** [comment]
> As a Persian library for the Persian-speaking community, I think providing documentation in Persian is essential.

@mhzendehpey Really appreciate your feedback Mohammad Hosein jan! You're right, we have to put this on the schedule.

**Comment by arxyzan** [comment]
> @arxyzan we can get help from the community for completing this task. I also think this is an essential feature we should add

I'm down for the README.md but providing a Persian version for other documents seems like a lot of work! We need to prioritize some important ones.

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, in the first draft we can start with only headers and titles in Persian and the rest can be applied gradually.
Totally agree with you that we need to discuss its priority.

**Comment by arxyzan** [comment]
Preferrably, we're going to publish Persian tutorials in blog formats on Virgool.io but having actual Persian documentation can be tough since all of our docs are in Markdown files which makes it hard to maintain for Persian due to RTL overheads.

**Comment by pooya-mohammadi** [comment]
Agreed @arxyzan jan, we should publish the Persian documents on a platform which is RTL friendly. I believe Virgool.io is a great alternative choice, as you mentioned.

**Comment by arxyzan** [comment]
Nice @pooya-mohammadi . Closing this issue ...
