### ISSUE TITLE
Refactor examples

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#110]
Examples are so all-over-the-place right now. We have to reorganize them into folders and rename most of them. 
Besides, they need to be more thorough and have docs/docstrings/comments so that users understand them easier.

If anyone wants to participate, just let us know by mentioning us (@pooya-mohammadi, @arxyzan) right here.

**Comment by SSBakh07** [comment]
Hey there! I'd love to contribute and help out however I can, both with documentation (English preferred, but Persian is fine too) and code! @pooya-mohammadi  @arxyzan 

How should I get started? 

(If need be, I can leave my Discord and/or Telegram username here (or email) so we talk more in depth.)

**Comment by arxyzan** [comment]
Hello @SSBakh07 and thanks for the offer. You can get started from anywhere you want. Our examples were initially the place where we used to test everything. Most of them are so straight to the point and have no specific style and additional notes specially in terms of docstrings. Currently they only offer really high-level usages. If you have already got your hands dirty with Hezar and (kind of) know how it works under the hood you can try to provide more in-depth examples. You can also focus on providing more enhanced examples in our [notebooks](https://github.com/hezarai/notebooks) repo. 

You can DM me (https://t.me/arxyzan) or Pooya (https://t.me/Pooya_Mohammadi_K) on Telegram too.

**Comment by SSBakh07** [comment]
Thanks, will do!
