### ISSUE TITLE
there is no guide to use of this library

### ISSUE THREAD

**Issue by muhammadCodeSh** [hezarai/hezar#119]
I am a beginner and just want to give a text to your library and get a summary of that text how can I do it,
please write an example,

**Comment by arxyzan** [comment]
Hello @muhammadCodeSh . Actually we're working on a text summarizer model right now and we'll publish it soon. We'll also include an example in the `README.md` file. But the general structure of such example is as below:
```python
from hezar.models import Model

model = Model.load("path/to/summarizer-model")
summary = model.predict("یک متن طولانی")
print(summary)
```

**Comment by muhammadCodeSh** [comment]
thanks for answer ,
