### ISSUE TITLE
finetune whisper-large

### ISSUE THREAD

**Issue by kontorol** [hezarai/hezar#137]
Hello. Thank you for your efforts. For fine-tuning Whisper-v3 using Hezar, what method do you suggest? If there is a sample similar to the one below, please introduce it. 
https://colab.research.google.com/github/Vaibhavs10/fast-whisper-finetuning/blob/main/Whisper_w_PEFT.ipynb

Thank you.

@arxyzan

**Comment by arxyzan** [comment]
Hello @kontorol, I really appreciate your feedback.
Unfortunately, there is no ready-to-use training script for speech recognition models in Hezar right now (The Trainer can handle speech recognition but the evaluation with metrics part is not ready yet). We have plans to finetune the new Whisper v3 on Persian and look forward to realease it in the coming month.
The notebook you provided can be used to do so with a few easy tweaks.
