### ISSUE TITLE
In night environments, how can license plate OCR be improved 

### ISSUE THREAD

**Issue by claymore07** [hezarai/hezar#148]
Hello,

My project desperately needs help. As I'm using the Hezarai OCR model to read license plates, I've encountered a problem where the model cannot read any characters from plates at night, while the characters can be clearly seen during the day. 

I am having trouble finding a solution to my problem. Since you have expertise in this area, could you help me?
![1](https://github.com/hezarai/hezar/assets/17278941/ad631264-3e87-4231-b3dc-342efc56f12f)

Best Regards

**Comment by arxyzan** [comment]
Hi @claymore07 ,
Unfortunately, the data we used to train our OCR model only contained images under daylight. The only solution is to collect night data and finetune the model on those samples too. As far as I know, we don't have such dataset openly available.
