### ISSUE TITLE
TypeError: transformers.generation.configuration_utils.GenerationConfig() argument after ** must be a mapping, not WhisperSpeechRecognitionGenerationConfig

### ISSUE THREAD

**Issue by hamed-dehghan** [hezarai/hezar#161]
When trying to use code snippet of the speech recognition this error occures:

![image](https://github.com/hezarai/hezar/assets/55046033/c99dda2b-5666-4060-9631-039603e5072e)

It hppens after running this code:

```python
from hezar.models import Model

model = Model.load("hezarai/whisper-small-fa")
transcripts = model.predict("examples/assets/speech_example.mp3")
print(transcripts)
```

**Comment by hamed-dehghan** [comment]
> Hi @hamed-dehghan thanks for the issue. What version are you using? I can verify that the bug exists on the main branch right now but not sure about the latest stable release (v.0.37.0).

Hi @arxyzan thank you for the response.
Yes I am using the main branch and my version is 0.37.0! kinda wierd!!

**Comment by hamed-dehghan** [comment]
> @hamed-dehghan The main branch does not necessarily have a different version w.r.t the stable. We update dev versions only on releases so it's okay if your version is 0.37.0. Anyway, I just commited a patch on main to resolve this so you can pull main again to make it work. But the stable version works too. Just run `pip install hezar`.

It worked...😍 Thank you @arxyzan

**Comment by arxyzan** [comment]
@hamed-dehghan Cool! 😉

**Comment by arxyzan** [comment]
Hi @hamed-dehghan, have you faced this issue again?
