### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by sahand-zeynol** [hezarai/hezar#170]
When trying to use code snippet of the license-plate-recognition this error occurs:
![Screenshot from 2024-06-27 22-31-23](https://github.com/hezarai/hezar/assets/59438138/5cae9f62-af70-4906-871d-ea79c8262ff8)

and as I checked it's because of type annotations, which are available in Python 3.10 and later. but for using Python 3.9 or earlier, this syntax is causing the error.

and you can fix with:
`generation_config: Optional[Union[dict, WhisperSpeechRecognitionGenerationConfig]] = None`

**Comment by arxyzan** [comment]
Hi @sahand-zeynol thanks for submitting this issue.
We recently dropped support for Python versions before 3.10. This let us use newer annotations syntax and better performance of Python itself.
