### ISSUE TITLE
Save training logs and reports to the hub in `Trainer.push_to_hub()`

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#58]
It makes sense to be able to push training results and reports like evaluation results to the hub when pushing a trainer to the hub.

**Comment by pooya-mohammadi** [comment]
If we want to save everything, we should use wandb or other monitoring systems.
In our case, we only want to final results. I believe we can have a text file showing a table of metrics.
In our main page, we can load this table and show it for our models.
@arxyzan

**Comment by arxyzan** [comment]
Done in c6c379f
