### ISSUE TITLE
Add roberta for sequence labeling

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#65]
Add Roberta model from Transformers for sequence labeling. See `BertSequenceLabeling` and `RobertaTextClassification` for references.

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, I'm on this

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, please check it, if you want I can train it for more epochs. Since we want to save the logs, I think it's better to postpone the second training until after decision making of our logging mechanism

**Comment by arxyzan** [comment]
@pooya-mohammadi Can you send a PR?

**Comment by pooya-mohammadi** [comment]
https://github.com/hezarai/hezar/pull/73
@arxyzan jan,
