### ISSUE TITLE
R&D CLIP model training and adding to the library

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#71]
This issue specifies the roadmap for adding CLIP to Hezar (model architecture, task, datasets, pretrained weights, etc)

**Comment by arxyzan** [comment]
The general steps to take:
- R&D model architecture, code and possibility of training the model
- R&D the preferred dataset
- R&D the required preprocessors and check if we already have them in Hezar
- R&D the implemented and trained models on Persian

Then, for each of these steps, open an issue.

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, I'm on it

**Comment by pooya-mohammadi** [comment]
Useful links: https://github.com/sajjjadayobi/CLIPfa
https://huggingface.co/datasets/amir7d0/laion20M-fa

**Comment by arxyzan** [comment]
This task has been postponed for later.
