### ISSUE TITLE
FineTune Whisper

### ISSUE THREAD

**Issue by pooya-mohammadi** [hezarai/hezar#72]
Use the following link to finetune on Mozila persian dataset
https://huggingface.co/blog/fine-tune-whisper

**Comment by arxyzan** [comment]
In order to train whisper in Hezar, we have to take the following steps:

- [x]  Add whisper model to the library
- [x] Add whisper preprocessors 
    - [x]  Feature extractor
    - [x] Tokenizer
- [ ] Implement SpeechRecognitionDataset
- [ ] Implement SpeechRecognitionTrainer
- [ ] Implement data collator for speech
