### ISSUE TITLE
Fix embedding outputs in Readme

### ISSUE THREAD

**Issue by pooya-mohammadi** [hezarai/hezar#75]
https://github.com/hezarai/hezar#word-embeddings
item: هزار
score: 0.65 (round)

**Comment by arxyzan** [comment]
@pooya-mohammadi 
I pushed a simple code for this but forogt to round it. can you check it out and fix it?

**Comment by pooya-mohammadi** [comment]
Yeah I will check it

**Comment by pooya-mohammadi** [comment]
@arxyzan jan, can we close this issue?

**Comment by arxyzan** [comment]
@pooya-mohammadi Sure man ;)
