### ISSUE TITLE
Add display like the one spacy has for NER

### ISSUE THREAD

**Issue by pooya-mohammadi** [hezarai/hezar#78]
![Screenshot from 2023-08-26 15-30-19](https://github.com/hezarai/hezar/assets/55460936/52f2631d-0719-4cda-a2a6-5596995e76d1)

**Comment by arxyzan** [comment]
I don't think this is a necessary feature right now. Besides, if Hezar is integrated with the HuggingFace Hub, the output is somehow like this one.
