### ISSUE TITLE
Add Persian portion of Google WIT dataset to our datasets

### ISSUE THREAD

**Issue by arxyzan** [hezarai/hezar#92]
Download and filter only Persian samples from WIT dataset (https://huggingface.co/datasets/google/wit) and upload to HF Hub.

**Comment by hosseinadib-hub** [comment]
If this task hasn't been done, I can do it.

**Comment by hosseinadib-hub** [comment]
Hello Aryan jan
no, I haven't had any experience adding a dataset before, but I don't think it's too difficult.

I believe this task can be divided into two parts, the first part involve extracting and filtering Persian samples, while the second part involve uploading them base on your format and templete.

**Comment by arxyzan** [comment]
Thanks Hossen jan,
Actually, it's not that easy. You have to write a data loading script for any dataset you want to push to the Hub. This loading script defines how the dataset is load, generated and constructed as a HF Dataset object. 
You can review some samples in the [templates folder](https://github.com/hezarai/hezar/tree/main/templates) to learn more.
